runtime: nodejs12
service: cms
instance_class: F2

handlers:
  - url: /favicon.ico
    static_files: /favicon.ico
    upload: /favicon.ico

  - url: /static
    static_dir: build/static

  - url: /(.*\.(json|ico|js))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js)$
    secure: always

  - url: .*
    static_files: build/index.html
    upload: build/index.html
